# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Lane to run the unit tests"
  lane :unit_tests do
    run_tests(device: "iPhone SE (3rd generation)", scheme: "OSInAppBrowserLib",
      slack_url: ENV['SLACK_WEBHOOK'])
  end

  desc "Code coverage"
  lane :coverage do
    slather(
      scheme: "OSInAppBrowserLib",
      proj: "OSInAppBrowserLib.xcodeproj",
      output_directory: "sonar-reports", 
      sonarqube_xml: "true"
    )
  end

  lane :lint do
    swiftlint(
      output_file: "sonar-reports/OSInAppBrowserLib-swiftlint.txt",
      ignore_exit_status: true
    )
  end

  lane :sonarqube do  
    sonar
  end
end
